version: "3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - "8000:80"
    networks:
      - internal
    volumes:
      - ./backend/:/var/www/
      - ./logs/nginx:/var/log/nginx/
    container_name: nginx

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./backend/:/var/www/
      - ./logs/php.log:/var/log/fpm-php.www.log
    container_name: php
    expose:
      - "9000"

  mysql:
    container_name: db
    restart: unless-stopped
    image: mysql:latest
    ports:
     - "3306:3306"
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - internal
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: 'root'
      PMA_PASSWORD: 'root'
    ports:
      - "8080:80"
    networks:
      - internal
    container_name: phpmyadmin

  react:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - internal

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - internal
    volumes:
      - mailhog_data:/data

networks:
  internal:
    driver: bridge

volumes:
  mailhog_data:
